/* ================================================================
   data-book1.js — obsah knihy 1
   Závisí na data-helpers.js (musí být načteno dřív)
   ================================================================ */

const BOOK1_PAGES = [

/* ═══ PRE-LESSON A ═══ */
{
  id:"pA", eyebrow:"Pre-Lesson A",
  title:"Výslovnost a základy japonštiny",
  subtitle:"Pronunciation Guide & The Basics",
  about:{
    before:["Žádné požadavky – je to úplný začátek"],
    goals:["Pochopit japonský zvukový systém","Poznat tři písma","Připravit se na hiraganu"],
    teachers:["Nespěchej – tato lekce staví základ pro vše ostatní"]
  },
  blocks:[
    {type:"p", text:"Pre-lekce A tě uvede do japonštiny bez jediného znaku – čistě slovem a zvukem. Než se vrhneš na psaní, chápat proč Japonci používají tři různá písma najednou."},
    {type:"h3", text:"Tři systémy písma"},
    {type:"p", text:"Japonština kombinuje tři odlišná písma: hiragana (ひらがな) — pro japonská slova a gramatiku; katakana (カタカナ) — pro přejatá cizí slova a jména; kanji (漢字) — znaky přejaté z čínštiny, každý s vlastním významem. V jedné větě se klidně střídají všechna tři."},
    {type:"tip", text:"Proč se učit hiraganu? Romaji (latinský přepis) je jen dočasná pomůcka. Jakmile zvládneš hiraganu, otevřou se ti dveře k autentickým textům — subtitlům, mangám, jídelním lístkům."},
    {type:"h3", text:"Japonská výslovnost"},
    {type:"p", text:"Japonské samohlásky jsou téměř totožné s češtinou: A = auto, I = iva, U = ucho, E = elo, O = oko. Nikdy je nevyslovuji anglicky. Každá slabika v japonštině má pevnou délku (mora) — na rozdíl od češtiny se délka přísně rozlišuje."},
    {type:"tip", text:"Tiché U: v rychlé mluvě se U v des(u) a mas(u) téměř nevyslovuje. \"Desu\" zní jako \"des\", \"tabemasu\" jako \"tabemas\". Je to přirozené — nesnažíš se to záměrně potlačit, přijde samo s praxí."},
    {type:"h3", text:"Dvojité souhlásky — malé っ"},
    {type:"p", text:"Malé っ (sokuon) znamená krátkou pauzu + zdvojení následující souhlásky. Gakkou (学校, škola) = ga-k-kou, kitte (切手, poštovní známka) = ki-t-te. Pauza trvá přesně jednu moru."},
  ],
  flashcardGroups:[{name:"Výslovnost — základy", cards:[
    {front:"A",frontKana:"あ",frontRo:"",back:"jako v češtině: auto"},
    {front:"I",frontKana:"い",frontRo:"",back:"jako v češtině: iva"},
    {front:"U",frontKana:"う",frontRo:"",back:"jako v češtině: ucho"},
    {front:"E",frontKana:"え",frontRo:"",back:"jako v češtině: elo"},
    {front:"O",frontKana:"お",frontRo:"",back:"jako v češtině: oko"},
    {front:"desu → des",frontKana:"です",frontRo:"",back:"U na konci se vyslovuje tiše"},
    {front:"malé っ",frontKana:"っ",frontRo:"",back:"pauza + zdvojení souhlásky"},
  ]}],
  quiz:[
    {q:"Který systém písma se používá pro přejatá cizí slova (koohii = káva)?",
     options:["Hiragana","Katakana","Kanji","Romaji"], correct:1,
     explain:"Katakana slouží pro přejatá slova, cizí jména a zvukomalebná slova."},
    {q:"Co způsobuje malé っ (sokuon) v japonském slově?",
     options:["Prodlužuje samohlásku","Krátká pauza + zdvojení následující souhlásky","Označuje konec věty","Nemění výslovnost"], correct:1},
  ]
},

/* ═══ PRE-LESSON B ═══ */
{
  id:"pB", eyebrow:"Pre-Lesson B",
  title:"Základní počítání",
  subtitle:"Basic Counting",
  about:{
    before:["Pre-Lesson A"],
    goals:["Naučit se čísla 1–10 000","Pochopit pravidla pro stovky a tisíce","Říct věk"],
    teachers:["Čísla 4, 7 a 9 mají dvě varianty — obě jsou správné, ale shi/shichi/ku se vyhýbají v citlivých kontextech"]
  },
  blocks:[
    {type:"words", headers:["Číslo","Kana","Kanji","Česky"], rows:[
      ["ichi","いち","一","1"], ["ni","に","二","2"], ["san","さん","三","3"],
      ["shi / yon","し・よん","四","4"], ["go","ご","五","5"],
      ["roku","ろく","六","6"], ["shichi / nana","しち・なな","七","7"],
      ["hachi","はち","八","8"], ["ku / kyuu","く・きゅう","九","9"],
      ["juu","じゅう","十","10"], ["hyaku","ひゃく","百","100"],
      ["sen","せん","千","1 000"], ["man","まん","万","10 000"],
    ]},
    {type:"tip", text:"Stovky mají nepravidelnosti: 300 = sanbyaku (さんびゃく), 600 = roppyaku (ろっぴゃく), 800 = happyaku (はっぴゃく). Tisíce: 3 000 = sanzEn (さんぜん), 8 000 = hassen (はっせん).", warn:true},
    {type:"culture", title:"Proč dvě verze čísla 4?", text:"Japonština má starý domácí systém číslování (hitotsu, futatsu…) i přejatý čínský (ichi, ni, san…). Shi (4) zní jako 死 (smrt) a ku (9) jako 苦 (bolest) — proto se v nemocnicích a hotelech místnosti s těmito čísly vynechávají. Alternativní varianty yon a nana jsou bezpečnější."},
    {type:"h3", text:"Složené čísla"},
    {type:"p", text:"Čísla se skládají od největšího po nejmenší: 2 358 = ni-sen san-byaku go-juu hachi. Teens: 11 = juu-ichi, 12 = juu-ni. Desítky: 20 = ni-juu, 45 = yon-juu-go."},
    {type:"h3", text:"Věk — Nansai desu ka?"},
    {type:"phrases", items:[
      {num:"1",en:"How old are you?",jp:"なんさい ですか。",ro:"Nansai desu ka."},
      {num:"2",en:"I am [X] years old.",jp:"[X]さい です。",ro:"[X]-sai desu."},
      {num:"3",en:"How old do I look?",jp:"なんさいに みえますか。",ro:"Nansai ni miemasu ka."},
    ]},
    {type:"tip", text:"20 let = hatachi (はたち) — nepravidelný tvar, jedná se o historický výraz. Jinak: 21 = ni-juu-issai, 30 = sanjussai."},
  ],
  flashcardGroups:[{name:"Čísla 1–10 000", cards:[
    {front:"1",frontKana:"いち",frontRo:"ichi",back:"ichi / いち"},
    {front:"2",frontKana:"に",frontRo:"ni",back:"ni / に"},
    {front:"3",frontKana:"さん",frontRo:"san",back:"san / さん"},
    {front:"4",frontKana:"し・よん",frontRo:"shi / yon",back:"shi / yon"},
    {front:"5",frontKana:"ご",frontRo:"go",back:"go / ご"},
    {front:"6",frontKana:"ろく",frontRo:"roku",back:"roku / ろく"},
    {front:"7",frontKana:"しち・なな",frontRo:"shichi / nana",back:"shichi / nana"},
    {front:"8",frontKana:"はち",frontRo:"hachi",back:"hachi / はち"},
    {front:"9",frontKana:"く・きゅう",frontRo:"ku / kyuu",back:"ku / kyuu"},
    {front:"10",frontKana:"じゅう",frontRo:"juu",back:"juu"},
    {front:"100",frontKana:"ひゃく",frontRo:"hyaku",back:"hyaku"},
    {front:"1 000",frontKana:"せん",frontRo:"sen",back:"sen"},
  ]}],
  quiz:[
    {q:"Jak se řekne 300?", options:["san-hyaku","san-byaku","san-pyaku","sab-hyaku"], correct:1,
     explain:"300 = sanbyaku — nepravidelné! Stejně: 600 = roppyaku, 800 = happyaku."},
    {q:"Jak se řekne číslo 2 358?",
     options:["ni-sen san-byaku go-juu hachi","ni-san-go-hachi","futatsu-san-go-hachi","ni-hyaku san-juu go-hachi"], correct:0},
    {q:"Jak se řekne '20 let'?",
     options:["ni-juu-sai","hatachi","ni-sai","futatsu-sai"], correct:1,
     explain:"20 let = hatachi — historický nepravidelný tvar."},
  ]
},

/* ═══ PRE-LESSON C ═══ */
{
  id:"pC", eyebrow:"Pre-Lesson C",
  title:"První setkání",
  subtitle:"First Meeting",
  about:{
    before:["Pre-Lessons A a B"],
    goals:["Představit se v japonštině","Říct věk a národnost","Zakončit představování správnou frází"],
    teachers:["Hajimemashite = začátek, Yoroshiku onegaishimasu = závěr — vždy v páru"]
  },
  blocks:[
    {type:"culture", title:"Úklona (お辞儀 ojigi)", text:"V Japonsku se místo podání ruky uklání. Čím hlubší úklona, tím větší respekt. Lehká úklona hlavy = mezi přáteli. Hluboká úklona z pasu = v obchodním kontextu nebo při omluvě. Pokud Japonec natáhne ruku, přijmi ji — ale neočekávej to."},
    {type:"phrases", items:[
      {num:"1",en:"How do you do? / Nice to meet you.",jp:"はじめまして。",ro:"Hajimemashite."},
      {num:"2",en:"My name is ___. (formální)",jp:"___ と もうします。",ro:"___ to moushimasu."},
      {num:"2b",en:"I am ___. (neformální)",jp:"___ です。",ro:"___ desu."},
      {num:"3",en:"I am [nationality].",jp:"[国籍]じん です。",ro:"[kokuseki]-jin desu."},
      {num:"4",en:"I am a student / teacher.",jp:"がくせい / せんせい です。",ro:"Gakusei / Sensei desu."},
      {num:"5",en:"Nice to meet you. (závěr)",jp:"よろしく おねがいします。",ro:"Yoroshiku onegaishimasu."},
      {num:"6",en:"Likewise. Nice to meet you too.",jp:"こちらこそ よろしく おねがいします。",ro:"Kochira koso yoroshiku onegaishimasu."},
    ]},
    {type:"dialogue", title:"Vzorový rozhovor — první setkání", lines:[
      {speaker:"Tanaka:", jp:"はじめまして。たなか と もうします。よろしく おねがいします。", en:"Těší mě. Jmenuji se Tanaka. Potěšilo mě."},
      {speaker:"Mike:", jp:"はじめまして。マイク です。よろしく おねがいします。", en:"Těší mě. Jsem Mike. Potěšilo mě."},
    ]},
    {type:"h3", text:"Věk v konverzaci"},
    {type:"tip", text:"Přímá otázka na věk v Japonsku není nezdvořilá — jde o velmi běžné konverzační téma. Buď připraven/a odpovědět nebo se zeptat zpět!"},
  ],
  flashcardGroups:[{name:"Fráze — první setkání", cards:[
    {front:"Hajimemashite",frontKana:"はじめまして",frontRo:"",back:"Těší mě / Nice to meet you"},
    {front:"___ to moushimasu",frontKana:"___ともうします",frontRo:"",back:"Jmenuji se ___ (formální)"},
    {front:"___ desu",frontKana:"___です",frontRo:"",back:"Jsem ___ (neformální)"},
    {front:"Yoroshiku onegaishimasu",frontKana:"よろしくおねがいします",frontRo:"",back:"Těší mě (závěrečná fráze)"},
    {front:"Kochira koso",frontKana:"こちらこそ",frontRo:"",back:"Rovněž / Taktéž"},
    {front:"Gakusei desu",frontKana:"がくせいです",frontRo:"",back:"Jsem student/ka"},
    {front:"Nansai desu ka",frontKana:"なんさいですか",frontRo:"",back:"Kolik je ti let?"},
  ]}],
  quiz:[
    {q:"Co říkáš při prvním setkání jako úvod?",
     options:["Yoroshiku onegaishimasu","Hajimemashite","Sumimasen","Konnichiwa"], correct:1,
     explain:"Hajimemashite zahajuje představování. Yoroshiku onegaishimasu ho uzavírá."},
    {q:"Jak formálně řekneš 'Jmenuji se Yamada'?",
     options:["Yamada desu","Yamada to moushimasu","Yamada ga suki desu","Yamada wa ii desu"], correct:1},
    {q:"Co znamená '-jin' (じん) v 'Nihonjin'?",
     options:["jazyk","člověk / příslušník národa","země","město"], correct:1,
     explain:"Jin (人) = člověk. Nihonjin = Japonec, Amerikajin = Američan, Chekojin = Čech."},
  ]
},

/* ═══ PRE-LESSON D ═══ */
{
  id:"pD", eyebrow:"Pre-Lesson D",
  title:"Přicházení a odcházení",
  subtitle:"Coming and Going",
  about:{
    before:["Pre-Lessons A, B, C"],
    goals:["Naučit se každodenní pozdravy","Fráze při odchodu z domu a návratu","Pochopit tiché U"],
    teachers:["Itte kimasu / Itterasshai a Tadaima / Okaerinasai — jsou to párové fráze, vždy v dvojici"]
  },
  blocks:[
    {type:"phrases", items:[
      {num:"1",en:"Good morning. (formální)",jp:"おはよう ございます。",ro:"Ohayou gozaimasu."},
      {num:"1b",en:"Good morning. (neformální)",jp:"おはよう。",ro:"Ohayou."},
      {num:"2",en:"Good afternoon.",jp:"こんにちは。",ro:"Konnichiwa."},
      {num:"3",en:"Good evening.",jp:"こんばんは。",ro:"Konbanwa."},
      {num:"4",en:"Good night.",jp:"おやすみ なさい。",ro:"Oyasumi nasai."},
      {num:"5",en:"Thank you. (formální)",jp:"ありがとう ございます。",ro:"Arigatou gozaimasu."},
      {num:"5b",en:"Thank you. (neformální)",jp:"ありがとう。",ro:"Arigatou."},
      {num:"6",en:"Excuse me. / I'm sorry.",jp:"すみません。",ro:"Sumimasen."},
      {num:"7",en:"I'm sorry. / Forgive me.",jp:"ごめんなさい。",ro:"Gomen nasai."},
      {num:"8",en:"Yes.",jp:"はい。",ro:"Hai."},
      {num:"9",en:"No.",jp:"いいえ。",ro:"Iie."},
    ]},
    {type:"dialogue", title:"Conversation 1 — Odchod z domu", lines:[
      {speaker:"Jirō:", jp:"いってきます！", en:"I'll go and come back!"},
      {speaker:"Matka:", jp:"いってらっしゃい。", en:"Have a good day! / Take care."},
    ]},
    {type:"dialogue", title:"Conversation 2 — Návrat domů", lines:[
      {speaker:"Jirō:", jp:"ただいま！", en:"I'm home! / I'm back!"},
      {speaker:"Matka:", jp:"おかえりなさい。", en:"Welcome back home."},
    ]},
    {type:"tip", text:"Tiché U: desu (です) se vyslovuje jako 'des', tabemasu (たべます) jako 'tabemas'. Samohláska U na konci -su a -tsu v rychlé řeči téměř zmizí — to je naprosto přirozené, nesnaž se ji uměle vyslovovat."},
    {type:"vocab", groupTitle:"Části těla (体 karada)", items:[
      {jp:"あたま",kana:"あたま",romaji:"atama",en:"hlava"},
      {jp:"め",kana:"め",romaji:"me",en:"oko"},
      {jp:"はな",kana:"はな",romaji:"hana",en:"nos"},
      {jp:"くち",kana:"くち",romaji:"kuchi",en:"ústa"},
      {jp:"みみ",kana:"みみ",romaji:"mimi",en:"ucho"},
      {jp:"て",kana:"て",romaji:"te",en:"ruka"},
      {jp:"あし",kana:"あし",romaji:"ashi",en:"noha / chodidlo"},
    ]},
    {type:"vocab", groupTitle:"Koupelna a ložnice", items:[
      {jp:"ベッド",kana:"ベッド",romaji:"beddo",en:"postel"},
      {jp:"まくら",kana:"まくら",romaji:"makura",en:"polštář"},
      {jp:"もうふ",kana:"もうふ",romaji:"moufu",en:"deka"},
      {jp:"タオル",kana:"タオル",romaji:"taoru",en:"ručník"},
      {jp:"せっけん",kana:"せっけん",romaji:"sekken",en:"mýdlo"},
      {jp:"はぶらし",kana:"はぶらし",romaji:"haburashi",en:"kartáček na zuby"},
    ]},
  ],
  flashcardGroups:[{name:"Každodenní fráze", cards:[
    {front:"Ohayou gozaimasu",frontKana:"おはようございます",frontRo:"",back:"Dobré ráno (formální)"},
    {front:"Ohayou",frontKana:"おはよう",frontRo:"",back:"Dobré ráno (neformální)"},
    {front:"Konnichiwa",frontKana:"こんにちは",frontRo:"",back:"Dobrý den"},
    {front:"Konbanwa",frontKana:"こんばんは",frontRo:"",back:"Dobrý večer"},
    {front:"Oyasumi nasai",frontKana:"おやすみなさい",frontRo:"",back:"Dobrou noc"},
    {front:"Arigatou gozaimasu",frontKana:"ありがとうございます",frontRo:"",back:"Děkuji (formální)"},
    {front:"Sumimasen",frontKana:"すみません",frontRo:"",back:"Promiňte / Pardon"},
    {front:"Gomen nasai",frontKana:"ごめんなさい",frontRo:"",back:"Omlouvám se"},
    {front:"Itte kimasu",frontKana:"いってきます",frontRo:"",back:"Jdu (a vrátím se)"},
    {front:"Itterasshai",frontKana:"いってらっしゃい",frontRo:"",back:"Sbohem / Odpověď na itte kimasu"},
    {front:"Tadaima",frontKana:"ただいま",frontRo:"",back:"Jsem zpátky!"},
    {front:"Okaerinasai",frontKana:"おかえりなさい",frontRo:"",back:"Vítej doma — odpověď na tadaima"},
  ]}],
  quiz:[
    {q:"Co odpovíš, když ti někdo řekne 'Itte kimasu'?",
     options:["Tadaima","Itterasshai","Okaerinasai","Hajimemashite"], correct:1,
     explain:"Itterasshai = odpověď na Itte kimasu. Okaerinasai = odpověď na Tadaima."},
    {q:"Proč se 'desu' vyslovuje spíš jako 'des'?",
     options:["Je to překlep","U se vyslovuje tiše nebo vůbec v pozici -su na konci slova","Záleží na dialektu","Jde o zdvořilou variantu"], correct:1},
    {q:"Jak neformálně pozdravíš ráno kamaráda?",
     options:["Ohayou gozaimasu","Konnichiwa","Ohayou","Konbanwa"], correct:2,
     explain:"Ohayou (bez gozaimasu) je neformální verze pro přátele a rodinu."},
  ]
},

/* ═══════════════════════ LESSON 1 ═══════════════════════ */
{
  id:"l1", eyebrow:"Lekce 1",
  title:"Creating Simple Sentences",
  subtitle:"Jednoduché věty · Hiragana あいうえお",
  about:{
    before:["Pre-lekce A–D","Čísla 1–10","Základní pozdravy"],
    goals:["Desu (です) — jednoduchá věta","Otázky s ka (か)","Tázací slovo nani / nan (co)","Hiragana あいうえお"],
    teachers:["Nezaměňuj あ a お — smyčka u お se připojuje k přímé čáře","Trénuj hiraganu psaním, ne jen pohledem"]
  },
  blocks:[
    {type:"words", headers:["Progressive","Kana","Kanji","Česky"], rows:[
      ["makura","まくら","枕","polštář"],
      ["moufu","もうふ","毛布","deka"],
      ["taoru","タオル","タオル","ručník"],
      ["sekken","せっけん","石鹸","mýdlo"],
      ["inu","いぬ","犬","pes"],
      ["neko","ねこ","猫","kočka"],
      ["hana","はな","花・鼻","květ / nos"],
      ["hai","はい","はい","ano"],
      ["iie","いいえ","いいえ","ne"],
      ["nan / nani","なん・なに","何","co"],
    ]},
    {type:"phrases", items:[
      {num:"1",en:"Do you understand?",jp:"わかりますか。",ro:"Wakarimasu ka."},
      {num:"2",en:"Yes, I understand.",jp:"はい、わかります。",ro:"Hai, wakarimasu."},
      {num:"3",en:"No, I don't understand.",jp:"いいえ、わかりません。",ro:"Iie, wakarimasen."},
      {num:"4",en:"I don't know. / I don't understand.",jp:"わかりません。",ro:"Wakarimasen."},
      {num:"5",en:"Please say it once again.",jp:"もう いちど いって ください。",ro:"Mou ichido itte kudasai."},
      {num:"6",en:"Please speak more slowly.",jp:"もっと ゆっくり いって ください。",ro:"Motto yukkuri itte kudasai."},
    ]},
    {type:"culture", title:"San (さん) — Mr. / Mrs. / Ms.",
      text:"San se přidává ZA příjmení nebo jméno jako zdvořilý titul — nikdy ho nepoužívej pro sebe! Tanaka-san = pan/paní Tanaka. Kun (くん) pro mladší muže, chan (ちゃん) pro děti a blízké přátele."},
    {type:"grammar", points:[
      {title:"Plurály v japonštině",
       body:"Japonština nerozlišuje jednotné a množné číslo pro většinu slov. Inu = pes i psi — záleží na kontextu. Žádné skloňování."},
      {title:"Desu (です) — věta",
       body:"Desu (vyslovuj 'des') funguje jako 'je / jsem / jsi'. Vždy na konci věty.",
       formula:"[slovo] + desu",
       examples:[
         {num:"1",jp:"まくら です。",ro:"Makura desu.",en:"Je to polštář."},
         {num:"2",jp:"たなか です。",ro:"Tanaka desu.",en:"Jsem Tanaka."},
         {num:"3",jp:"こばやし さん です。",ro:"Kobayashi-san desu.",en:"Je to slečna Kobayashi."},
       ]},
      {title:"Otázky s ka (か)",
       body:"Přidáním か na konec desu-věty z ní uděláš otázku. Žádná změna slovosledu!",
       formula:"[slovo] + desu + ka → otázka",
       examples:[
         {num:"1",jp:"まくら ですか。",ro:"Makura desu ka.",en:"Je to polštář?"},
         {num:"2",jp:"たなか さん ですか。",ro:"Tanaka-san desu ka.",en:"Jsi pan Tanaka?"},
       ]},
      {title:"Nani / Nan (何) — co",
       body:"Nan se používá před desu a d-zvuky. Nani jinde. Obě znamenají 'co'.",
       formula:"nan + desu + ka → Co je to?",
       examples:[
         {num:"1",jp:"なん ですか。",ro:"Nan desu ka.",en:"Co je to?"},
         {num:"2",jp:"これ は なん ですか。",ro:"Kore wa nan desu ka.",en:"Co je tohle?"},
       ]},
    ]},
    {type:"kana", rows:[...H_AIUEO]},
    {type:"tip", text:"Psaní あ vs お: druhý tah あ je zakřivený a NEPŘIPOJUJE se ke smyčce. Druhý tah お je rovný a ke smyčce SE připojuje. Jsou si vizuálně podobné — věnuj jim zvláštní pozornost!"},
    {type:"qa", title:"Q&A cvičení E→J", titleJp:"Q&A E→J", pairs:[
      {en:"What is it?",jp:"なん ですか。"},
      {en:"It is a pillow.",jp:"まくら です。"},
      {en:"Is it a towel?",jp:"タオル ですか。"},
      {en:"No, it is a blanket.",jp:"いいえ、もうふ です。"},
      {en:"Do you understand?",jp:"わかりますか。"},
      {en:"No, I don't understand.",jp:"いいえ、わかりません。"},
    ]},
    {type:"sentence", jp:"なん ですか。", en:"Co je to?"},
    {type:"vocab", groupTitle:"Domácnost", items:[
      {jp:"まくら",kana:"まくら",romaji:"makura",en:"polštář"},
      {jp:"もうふ",kana:"もうふ",romaji:"moufu",en:"deka"},
      {jp:"タオル",kana:"タオル",romaji:"taoru",en:"ručník"},
      {jp:"せっけん",kana:"せっけん",romaji:"sekken",en:"mýdlo"},
      {jp:"ふとん",kana:"ふとん",romaji:"futon",en:"futon"},
      {jp:"かがみ",kana:"かがみ",romaji:"kagami",en:"zrcadlo"},
    ]},
  ],
  flashcardGroups:[
    {name:"Hiragana あいうえお", cards: kanaCards(H_AIUEO)},
    {name:"Slovíčka L1", cards:[
      {front:"まくら",frontKana:"",frontRo:"makura",back:"polštář"},
      {front:"もうふ",frontKana:"",frontRo:"moufu",back:"deka"},
      {front:"タオル",frontKana:"",frontRo:"taoru",back:"ručník"},
      {front:"せっけん",frontKana:"",frontRo:"sekken",back:"mýdlo"},
      {front:"いぬ",frontKana:"",frontRo:"inu",back:"pes"},
      {front:"ねこ",frontKana:"",frontRo:"neko",back:"kočka"},
      {front:"なん",frontKana:"",frontRo:"nan",back:"co"},
    ]},
    {name:"Fráze L1", cards:[
      {front:"Wakarimasu ka",frontKana:"わかりますか",frontRo:"",back:"Rozumíš? / Víš?"},
      {front:"Wakarimasen",frontKana:"わかりません",frontRo:"",back:"Nerozumím. / Nevím."},
      {front:"Mou ichido itte kudasai",frontKana:"もういちどいってください",frontRo:"",back:"Řekni to ještě jednou."},
      {front:"Motto yukkuri itte kudasai",frontKana:"もっとゆっくりいってください",frontRo:"",back:"Mluv pomaleji."},
    ]},
  ],
  quiz:[
    {q:"Jaká hiragana odpovídá slabice 'a'?",
     options:["あ","お","う","え"], correct:0},
    {q:"Jaká hiragana odpovídá slabice 'o'?",
     options:["あ","い","う","お"], correct:3},
    {q:"Co přidáš na konec věty, aby se stala otázkou?",
     options:["は","が","か","の"], correct:2,
     explain:"か (ka) na konci věty tvoří otázku — bez změny slovosledu."},
    {q:"Jak japonsky řekneš 'Je to mýdlo'?",
     options:["せっけん ですか","せっけん じゃない","せっけん です","せっけん か"], correct:2},
    {q:"Co znamená Wakarimasen?",
     options:["Rozumím.","Nerozumím / Nevím.","Prosím.","Děkuji."], correct:1},
    {q:"San (さん) v japonštině je:",
     options:["Číslo 3","Zdvořilý titul za jménem","Pozdrav","Zápor"], correct:1,
     explain:"San = Mr./Mrs./Ms. Přidává se za jméno nebo příjmení. Nikdy pro sebe!"},
  ]
},

/* ═══════════════════════ LESSON 2 ═══════════════════════ */
{
  id:"l2", eyebrow:"Lekce 2",
  title:"Working with a Topic",
  subtitle:"Téma věty · Hiragana かきくけこ",
  about:{
    before:["Ovládnout あいうえお","Rozumět desu a otázkám s か"],
    goals:["Téma věty s wa (は)","Ko-so-a-do vzorec","Tázací slova dore a docchi","Vypouštění tématu"],
    teachers:["Zapamatuj si ko-so-a-do — vrátí se v každé lekci","90 % odpovědi je obsaženo v otázce"]
  },
  blocks:[
    {type:"words", headers:["Progressive","Kana","Kanji","Česky"], rows:[
      ["dore","どれ","どれ","který? (ze 3+)"],
      ["kore","これ","これ","tenhle (u mluvčího)"],
      ["sore","それ","それ","tamten (u posluchače)"],
      ["are","あれ","あれ","tamten (daleko)"],
      ["docchi","どっち","どっち","který? (ze 2)"],
      ["kocchi","こっち","こっち","tento (ze 2)"],
      ["socchi","そっち","そっち","tamten (ze 2)"],
      ["retasu","レタス","レタス","salát"],
      ["banana","バナナ","バナナ","banán"],
      ["yasai","やさい","野菜","zelenina"],
      ["furuutsu","フルーツ","フルーツ","ovoce (cizí slovo)"],
      ["kudamono","くだもの","果物","ovoce (japonské slovo)"],
      ["sushi","すし","寿司","sushi"],
      ["pen","ペン","ペン","pero"],
      ["kuruma","くるま","車","auto"],
      ["hon","ほん","本","kniha"],
      ["zasshi","ざっし","雑誌","časopis"],
    ]},
    {type:"phrases", items:[
      {num:"1",en:"Can you speak Japanese?",jp:"にほんご が はなせますか。",ro:"Nihongo ga hanasemasu ka."},
      {num:"2",en:"A little.",jp:"すこし。",ro:"Sukoshi."},
      {num:"3",en:"Not at all.",jp:"ぜんぜん。",ro:"Zenzen."},
      {num:"4",en:"I am studying Japanese.",jp:"にほんご を べんきょう しています。",ro:"Nihongo o benkyou shiteimasu."},
    ]},
    {type:"culture", title:"Sushi a Sashimi",
      text:"Sushi = syrové nebo vařené ryby / vejce / zelenina na hrsti rýže s wasabi. Sashimi = jen nakrájená syrová ryba bez rýže. Wasabi (わさび) je ostrý japonský křen."},
    {type:"cool", title:"Ko-So-A-Do vzorec",
      text:"Japonština má 4 kategorie slov odvozených od předpon: KO- (blízko mluvčímu), SO- (blízko posluchači), A- (daleko od obou), DO- (tázací). Platí pro věci (kore/sore/are/dore), místa (koko/soko/asoko/doko), směr (kochira/sochira/achira/dochira) i přídavná jména (konna/sonna/anna/donna). Je to jeden z nejdůležitějších vzorců v japonštině!"},
    {type:"grammar", points:[
      {title:"Téma věty — wa (は)",
       body:"Částice wa označuje téma věty. Vše před wa je téma, vše za wa ho popisuje. Pozor: wa se píše は, ale jako tato částice se čte 'wa' (ne 'ha').",
       formula:"[téma] + wa + [popis nebo otázka]",
       examples:[
         {num:"1",jp:"バナナ は きいろ です。",ro:"Banana wa kiiro desu.",en:"Banány jsou žluté."},
         {num:"2",jp:"これ は なん ですか。",ro:"Kore wa nan desu ka.",en:"Co je tohle?"},
         {num:"3",jp:"ゆかり さん は にほんじん です。",ro:"Yukari-san wa nihonjin desu.",en:"Yukari je Japonka."},
       ]},
      {title:"Dore vs. Docchi",
       body:"Dore (どれ) = který ze tří a více. Docchi (どっち) = který ze dvou. V odpovědi zachovej stejný styl — docchi otázka → kocchi/socchi/acchi odpověď.",
       formula:"[téma] wa dore / docchi desu ka",
       examples:[
         {num:"1",jp:"くるま は どれ ですか。",ro:"Kuruma wa dore desu ka.",en:"Které je auto? (3+ aut)"},
         {num:"2",jp:"くるま は どっち ですか。",ro:"Kuruma wa docchi desu ka.",en:"Které je auto? (2 auta)"},
       ]},
      {title:"Vypouštění tématu",
       body:"Po prvním uvedení tématu ho japonština vynechává — na rozdíl od češtiny, kde opakujeme 'on/ona/ono'.",
       examples:[
         {num:"1",jp:"わたし の ともだち は みちこ さん です。",ro:"",en:"Moje přítelkyně je Michiko."},
         {num:"2",jp:"にほん に すんでいます。",ro:"",en:"[Ona] žije v Japonsku."},
         {num:"3",jp:"じゅうはっさい です。",ro:"",en:"[Jí] je 18 let."},
       ]},
    ]},
    {type:"kana", rows:[...H_KA]},
    {type:"tip", text:"Dakuten (゛) přidané ke か き く け こ mění je na が ぎ ぐ げ ご (g-řada). Dvě malé čárky vpravo nahoře. Dávej pozor na psaní が — druhý tah se zatáčí zpět dolů a dovnitř."},
    {type:"qa", title:"Q&A cvičení E→J", titleJp:"Q&A E→J", pairs:[
      {en:"What is this?",jp:"これ は なん ですか。"},
      {en:"This is a pillow.",jp:"これ は まくら です。"},
      {en:"Which one is it? (3 items)",jp:"どれ ですか。"},
      {en:"It is this one.",jp:"これ です。"},
      {en:"Which one? (2 items)",jp:"どっち ですか。"},
      {en:"That one.",jp:"そっち です。"},
      {en:"Is this a vegetable?",jp:"これ は やさい ですか。"},
      {en:"No, that is a fruit.",jp:"いいえ、フルーツ です。"},
    ]},
    {type:"sentence", jp:"くるま は なん ですか。", en:"Co je to auto?"},
    {type:"vocab", groupTitle:"Rodina (家族 kazoku)", items:[
      {jp:"おとうさん",kana:"おとうさん",romaji:"otousan",en:"táta"},
      {jp:"おかあさん",kana:"おかあさん",romaji:"okaasan",en:"máma"},
      {jp:"おにいさん",kana:"おにいさん",romaji:"oniisan",en:"starší bratr"},
      {jp:"おねえさん",kana:"おねえさん",romaji:"oneesan",en:"starší sestra"},
      {jp:"おとうと",kana:"おとうと",romaji:"otouto",en:"mladší bratr"},
      {jp:"いもうと",kana:"いもうと",romaji:"imouto",en:"mladší sestra"},
    ]},
  ],
  flashcardGroups:[
    {name:"Hiragana かきくけこ", cards: kanaCards(H_KA)},
    {name:"Ko-So-A-Do", cards:[
      {front:"これ",frontKana:"",frontRo:"kore",back:"tenhle (u mluvčího)"},
      {front:"それ",frontKana:"",frontRo:"sore",back:"tamten (u posluchače)"},
      {front:"あれ",frontKana:"",frontRo:"are",back:"tamten (daleko)"},
      {front:"どれ",frontKana:"",frontRo:"dore",back:"který? (ze 3+)"},
      {front:"こっち",frontKana:"",frontRo:"kocchi",back:"tento (ze 2)"},
      {front:"そっち",frontKana:"",frontRo:"socchi",back:"tamten (ze 2)"},
      {front:"どっち",frontKana:"",frontRo:"docchi",back:"který? (ze 2)"},
    ]},
    {name:"Slovíčka L2", cards:[
      {front:"くるま",frontKana:"",frontRo:"kuruma",back:"auto"},
      {front:"ほん",frontKana:"",frontRo:"hon",back:"kniha"},
      {front:"ざっし",frontKana:"",frontRo:"zasshi",back:"časopis"},
      {front:"やさい",frontKana:"",frontRo:"yasai",back:"zelenina"},
      {front:"くだもの",frontKana:"",frontRo:"kudamono",back:"ovoce"},
      {front:"すし",frontKana:"",frontRo:"sushi",back:"sushi"},
    ]},
  ],
  quiz:[
    {q:"Jaká hiragana odpovídá slabice 'ki'?",
     options:["か","き","く","け"], correct:1},
    {q:"Jak se čte は jako tématická částice?",
     options:["ha","wa","ba","ka"], correct:1,
     explain:"は jako tématická částice se čte 'wa', ne 'ha'."},
    {q:"Rozdíl mezi dore a docchi?",
     options:["Synonyma","Dore = ze 3+, Docchi = ze 2","Dore = ze 2, Docchi = ze 3+","Dore je zdvořilejší"], correct:1},
    {q:"Co znamená ko-so-a-do vzorec?",
     options:["Barvy","Předpony pro vzdálenost (KO-blízko, SO-u posluchače, A-daleko, DO-otázka)","Číslovky","Přídavná jména"], correct:1},
  ]
},

/* ═══════════════════════ LESSON 3 ═══════════════════════ */
{
  id:"l3", eyebrow:"Lekce 3",
  title:"Possession",
  subtitle:"Přivlastňování · Hiragana さしすせそ",
  about:{
    before:["Ovládnout あいうえお, かきくけこ","Chápat wa jako téma"],
    goals:["Tázací slovo dare (kdo)","Přivlastnění s no (の)","Začínat větu tázacím slovem + が"],
    teachers:["No = jako apostrof-s v angličtině","Dare ga = kdo dělá? Dare no = čí je?"]
  },
  blocks:[
    {type:"words", headers:["Progressive","Kana","Kanji","Česky"], rows:[
      ["dare","だれ","誰","kdo"],
      ["watashi","わたし","私","já"],
      ["anata","あなた","あなた","ty (zdvořilé)"],
      ["kare","かれ","彼","on"],
      ["kanojo","かのじょ","彼女","ona / přítelkyně"],
      ["tomodachi","ともだち","友達","přítel"],
      ["sensei","せんせい","先生","učitel / mistr"],
      ["namae","なまえ","名前","jméno"],
      ["usagi","うさぎ","兎","králík"],
      ["tori","とり","鳥","pták"],
    ]},
    {type:"culture", title:"Boku (ぼく) — různá slova pro 'já'",
      text:"Watashi (わたし) = neutrální, pro všechny. Boku (ぼく) = neformální mužské. Ore (おれ) = drsné mužské. Atashi (あたし) = ženské neformální. Výběr 'já' hodně říká o mluvčím!"},
    {type:"grammar", points:[
      {title:"Dare (誰) — kdo",
       body:"Dare funguje stejně jako nani a dore — vkládáš ho do věty.",
       examples:[
         {num:"1",jp:"だれ ですか。",ro:"Dare desu ka.",en:"Kdo to je?"},
         {num:"2",jp:"かれ は だれ ですか。",ro:"Kare wa dare desu ka.",en:"Kdo je on?"},
         {num:"3",jp:"せんせい は だれ ですか。",ro:"Sensei wa dare desu ka.",en:"Kdo je učitel?"},
       ]},
      {title:"Přivlastnění s no (の)",
       body:"No přidané za slovo ho převede do přivlastňovacího tvaru. Lze řetězit více no za sebou.",
       formula:"[slovo] + no = [slovo]'s",
       examples:[
         {num:"1",jp:"わたし の くるま",ro:"watashi no kuruma",en:"moje auto"},
         {num:"2",jp:"たなか さん の ねこ",ro:"Tanaka-san no neko",en:"Tanakova kočka"},
         {num:"3",jp:"わたし の ともだち の なまえ",ro:"watashi no tomodachi no namae",en:"jméno mého přítele"},
         {num:"4",jp:"これ は だれ の くるま ですか。",ro:"Kore wa dare no kuruma desu ka.",en:"Čí je tohle auto?"},
       ]},
      {title:"Tázací slovo + が jako téma",
       body:"Japonsky NEZAČÍNÁŠ větu tázacím slovem jako v češtině. VÝJIMKA: pokud je tázací slovo téma věty, MUSÍŠ použít が, ne は.",
       examples:[
         {num:"1",jp:"どれ が くるま ですか。",ro:"Dore ga kuruma desu ka.",en:"Které z nich je auto? ✓"},
         {num:"2",jp:"だれ が せんせい ですか。",ro:"Dare ga sensei desu ka.",en:"Kdo je učitel? ✓"},
         {num:"!",jp:"だれ は せんせい ですか。",ro:"",en:"✗ ŠPATNĚ — tázací slovo nesmí s は!"},
       ]},
    ]},
    {type:"kana", rows:[...H_SA]},
    {type:"tip", text:"Shi (し) — výjimka v SA-řadě: čte se 'shi', ne 'si'. Je to nejdůležitější výjimka celé SA-řady. Ostatní jsou pravidelné."},
    {type:"qa", title:"Q&A cvičení", titleJp:"Q&A", pairs:[
      {en:"Who is it?",jp:"だれ ですか。"},
      {en:"It's me.",jp:"わたし です。"},
      {en:"Whose car is it?",jp:"だれ の くるま ですか。"},
      {en:"It's my car.",jp:"わたし の くるま です。"},
      {en:"Which one is your rabbit?",jp:"どっち が あなた の うさぎ ですか。"},
    ]},
    {type:"sentence", jp:"これ は だれ の ですか。", en:"Čí je tohle?"},
    {type:"vocab", groupTitle:"Zvířata (動物 doubutsu)", items:[
      {jp:"いぬ",kana:"いぬ",romaji:"inu",en:"pes"},
      {jp:"ねこ",kana:"ねこ",romaji:"neko",en:"kočka"},
      {jp:"うさぎ",kana:"うさぎ",romaji:"usagi",en:"králík"},
      {jp:"とり",kana:"とり",romaji:"tori",en:"pták"},
      {jp:"さかな",kana:"さかな",romaji:"sakana",en:"ryba"},
      {jp:"うま",kana:"うま",romaji:"uma",en:"kůň"},
      {jp:"ぶた",kana:"ぶた",romaji:"buta",en:"prase"},
      {jp:"くま",kana:"くま",romaji:"kuma",en:"medvěd"},
    ]},
  ],
  flashcardGroups:[
    {name:"Hiragana さしすせそ", cards: kanaCards(H_SA)},
    {name:"Přivlastnění — no の", cards:[
      {front:"watashi no",frontKana:"わたしの",frontRo:"",back:"můj / moje"},
      {front:"anata no",frontKana:"あなたの",frontRo:"",back:"tvůj / tvoje"},
      {front:"dare no",frontKana:"だれの",frontRo:"",back:"čí?"},
      {front:"Tanaka-san no kuruma",frontKana:"たなかさんのくるま",frontRo:"",back:"Tanakovo auto"},
    ]},
    {name:"Slovíčka L3", cards:[
      {front:"だれ",frontKana:"",frontRo:"dare",back:"kdo"},
      {front:"わたし",frontKana:"",frontRo:"watashi",back:"já (neutrální)"},
      {front:"ともだち",frontKana:"",frontRo:"tomodachi",back:"přítel"},
      {front:"せんせい",frontKana:"",frontRo:"sensei",back:"učitel / mistr"},
      {front:"なまえ",frontKana:"",frontRo:"namae",back:"jméno"},
      {front:"うさぎ",frontKana:"",frontRo:"usagi",back:"králík"},
    ]},
  ],
  quiz:[
    {q:"Jaká hiragana odpovídá slabice 'shi'?",
     options:["さ","す","し","せ"], correct:2,
     explain:"し = shi — výjimka v SA-řadě."},
    {q:"Jak japonsky řekneš 'moje auto'?",
     options:["わたし くるま","くるま わたし","わたし の くるま","くるま の わたし"], correct:2},
    {q:"Kdy MUSÍŠ použít が místo は?",
     options:["Vždy","Nikdy","Když je tázací slovo tématem věty","Jen v minulém čase"], correct:2,
     explain:"Tázací slovo + が: Dare GA sensei desu ka? NIKDY dare WA."},
    {q:"Co znamená 'Tanaka-san no desu'?",
     options:["Pan Tanaka se ptá","Je to Tanakovo","Tanaka je učitel","Pan Tanaka ne"], correct:1},
  ]
},

/* ═══════════════════════ LESSON 4 ═══════════════════════ */
{
  id:"l4", eyebrow:"Lekce 4",
  title:"Colors and Adjectives",
  subtitle:"Barvy a přídavná jména · Hiragana たちつてと",
  about:{
    before:["Ovládnout SA-řadu","Chápat no (の) jako přivlastnění"],
    goals:["Částice to (と) — a, s","Barvy jako no-adjektiva","I-adjektiva (adj. na -i)","Barvy k popisu věcí"],
    teachers:["Barvy jako podst. jm. POTŘEBUJÍ no. I-formy barev (-oi) no NEpotřebují","Midori (zelená) nemá i-formu!"]
  },
  blocks:[
    {type:"words", headers:["Progressive","Kana","Kanji","Česky"], rows:[
      ["aka / akai","あか・あかい","赤・赤い","červená (podst.jm./příd.jm.)"],
      ["ao / aoi","あお・あおい","青・青い","modrá"],
      ["shiro / shiroi","しろ・しろい","白・白い","bílá"],
      ["kuro / kuroi","くろ・くろい","黒・黒い","černá"],
      ["chairo / chairoi","ちゃいろ・ちゃいろい","茶色・茶色い","hnědá"],
      ["kiiro / kiiroi","きいろ・きいろい","黄色・黄色い","žlutá"],
      ["midori","みどり","緑","zelená (bez i-formy!)"],
      ["orenji","オレンジ","オレンジ","oranžová"],
      ["pinku","ピンク","ピンク","růžová"],
      ["murasaki","むらさき","紫","fialová"],
      ["guree","グレー","グレー","šedá"],
      ["nani iro","なにいろ","何色","jaká barva?"],
    ]},
    {type:"phrases", items:[
      {num:"1",en:"What is it in Japanese?",jp:"にほんご で なん ですか。",ro:"Nihongo de nan desu ka."},
      {num:"2",en:"What is it in English?",jp:"えいご で なん ですか。",ro:"Eigo de nan desu ka."},
    ]},
    {type:"culture", title:"Green is Blue? (みどり は あお?)",
      text:"Japonci někdy označují věci, které my vidíme jako zelené, slovem aoi (modrý). Zelené semafor je 'modrý'. Zelená jablka jsou 'modrá'. Je to historická záležitost — původně aoi pokrývalo celé spektrum od modré po zelenou."},
    {type:"grammar", points:[
      {title:"Částice to (と) — seznam",
       body:"To (と) = 'a' v seznamu podstatných jmen. Nelze použít ke spojení celých vět.",
       formula:"[slovo1] + to + [slovo2] (+ to + [slovo3]…)",
       examples:[
         {num:"1",jp:"あお と むらさき と ピンク",ro:"ao to murasaki to pinku",en:"modrá, fialová a růžová"},
         {num:"2",jp:"ともだち の ねこ は ちゃいろ と しろ です。",ro:"",en:"Kočka přítele je hnědá a bílá."},
       ]},
      {title:"Barvy jako no-adjektiva",
       body:"Základní formy barev jsou podstatná jména. K popisu věci musíš přidat no.",
       formula:"[barva] + no + [věc]",
       examples:[
         {num:"1",jp:"みどり の くるま",ro:"midori no kuruma",en:"zelené auto"},
         {num:"2",jp:"しろ の うさぎ",ro:"shiro no usagi",en:"bílý králík"},
       ]},
      {title:"I-adjektiva (い形容詞)",
       body:"Základní barvy mají i-formu — adjektivum bez no, jde přímo před podstatné jméno. Vždy končí na -i.",
       formula:"[barva-i] + [věc]  (BEZ no)",
       examples:[
         {num:"1",jp:"あかい くるま ✓",ro:"akai kuruma",en:"červené auto (i-forma)"},
         {num:"2",jp:"あか くるま ✗",ro:"",en:"ŠPATNĚ — bez no ani i-formy"},
         {num:"3",jp:"みどり の くるま ✓ (midori nemá i-formu!)",ro:"",en:"zelené auto — vždy no"},
       ]},
    ]},
    {type:"kana", rows:[...H_TA]},
    {type:"tip", text:"TA-řada má tři výjimky: ち = chi (ne 'ti'), つ = tsu (ne 'tu'), ふ bude v H-řadě. Sokuon (malé っ): gakkou (学校), kitte (切手) — krátká pauza!"},
    {type:"qa", title:"Q&A cvičení", titleJp:"Q&A", pairs:[
      {en:"What color is it?",jp:"なにいろ ですか。"},
      {en:"It's black.",jp:"くろ です。"},
      {en:"What color car is it?",jp:"なにいろ の くるま ですか。"},
      {en:"It's a green car.",jp:"みどり の くるま です。"},
      {en:"Is your toothbrush blue?",jp:"あなた の はぶらし は あお ですか。"},
      {en:"No, mine is white.",jp:"いいえ、わたし の は しろ です。"},
    ]},
    {type:"sentence", jp:"くるま は なにいろ ですか。", en:"Jakou má barvu to auto?"},
    {type:"vocab", groupTitle:"Věci v domácnosti", items:[
      {jp:"テレビ",kana:"テレビ",romaji:"terebi",en:"televize"},
      {jp:"でんわ",kana:"でんわ",romaji:"denwa",en:"telefon"},
      {jp:"いす",kana:"いす",romaji:"isu",en:"židle"},
      {jp:"つくえ",kana:"つくえ",romaji:"tsukue",en:"stůl"},
      {jp:"まど",kana:"まど",romaji:"mado",en:"okno"},
      {jp:"ドア",kana:"ドア",romaji:"doa",en:"dveře"},
    ]},
  ],
  flashcardGroups:[
    {name:"Hiragana たちつてと", cards: kanaCards(H_TA)},
    {name:"Barvy", cards:[
      {front:"赤",frontKana:"あか",frontRo:"aka / akai",back:"červená"},
      {front:"青",frontKana:"あお",frontRo:"ao / aoi",back:"modrá"},
      {front:"白",frontKana:"しろ",frontRo:"shiro / shiroi",back:"bílá"},
      {front:"黒",frontKana:"くろ",frontRo:"kuro / kuroi",back:"černá"},
      {front:"茶色",frontKana:"ちゃいろ",frontRo:"chairo",back:"hnědá"},
      {front:"黄色",frontKana:"きいろ",frontRo:"kiiro / kiiroi",back:"žlutá"},
      {front:"緑",frontKana:"みどり",frontRo:"midori",back:"zelená (bez i-formy!)"},
      {front:"ピンク",frontKana:"ピンク",frontRo:"pinku",back:"růžová"},
      {front:"紫",frontKana:"むらさき",frontRo:"murasaki",back:"fialová"},
    ]},
  ],
  quiz:[
    {q:"Jaká hiragana odpovídá slabice 'chi'?",
     options:["た","つ","て","ち"], correct:3},
    {q:"Jak řekneš 'zelené auto'?",
     options:["みどり くるま","みどり の くるま","みどりい くるま","みどりい の くるま"], correct:1,
     explain:"Midori nemá i-formu — vždy potřebuje no: midori no kuruma."},
    {q:"Co je špatně na 'aka kuruma'?",
     options:["Nic — je to správně","Aka jako podst.jm. potřebuje no, nebo použij i-formu akai","Kuruma musí být první","Chybí desu"], correct:1},
    {q:"Jaká je funkce částice と (to)?",
     options:["Téma věty","Přivlastnění","Spojení podstatných jmen (a, s)","Otázka"], correct:2},
  ]
},

/* ═══════════════════════ LESSON 5 ═══════════════════════ */
{
  id:"l5", eyebrow:"Lekce 5",
  title:"Likes and Dislikes",
  subtitle:"Mít rád / nemít rád · Hiragana なにぬねの",
  about:{
    before:["I-adjektiva","Chápat が jako podmět"],
    goals:["が s suki a kirai","Negace ja nai","'One' pronoun s no","Výraz ja a"],
    teachers:["Suki a kirai VŽDY potřebují が pro věc","Kirai je drsné — raději suki ja nai"]
  },
  blocks:[
    {type:"words", headers:["Progressive","Kana","Kanji","Česky"], rows:[
      ["suki","すき","好き","mít rád"],
      ["kirai","きらい","嫌い","nemít rád"],
      ["daisuki","だいすき","大好き","zbožňovat"],
      ["daikirai","だいきらい","大嫌い","nesnášet"],
      ["oishii","おいしい","美味しい","chutný"],
      ["oishikunai","おいしくない","美味しくない","nechutný"],
      ["shigoto","しごと","仕事","práce"],
      ["kaimono","かいもの","買い物","nakupování"],
      ["ryokou","りょこう","旅行","cestování"],
      ["shukudai","しゅくだい","宿題","domácí úkol"],
      ["chikin","チキン","チキン","kuřecí maso"],
      ["nihongo","にほんご","日本語","japonský jazyk"],
      ["ja a","じゃあ","じゃあ","no tak / tedy"],
    ]},
    {type:"grammar", points:[
      {title:"が s suki (好き) a kirai (嫌い)",
       body:"Věc, která se líbí, dostává が. Ty sám/sama jsi téma (は).",
       formula:"[osoba] wa [věc] ga suki / kirai desu",
       examples:[
         {num:"1",jp:"わたし は いちご が すき です。",ro:"Watashi wa ichigo ga suki desu.",en:"Mám rád jahody."},
         {num:"2",jp:"わたし は チキン が だいすき です。",ro:"",en:"Zbožňuji kuřecí maso."},
         {num:"3",jp:"わたし は しゅくだい が だいきらい です。",ro:"",en:"Nesnáším domácí úkoly."},
       ]},
      {title:"Negace ja nai — 'není to'",
       body:"Ja nai přidáš za podstatné jméno nebo za suki/kirai. Neformální — formálněji de wa arimasen.",
       formula:"[podst.jm.] + ja nai desu",
       examples:[
         {num:"1",jp:"いぬ じゃない です。",ro:"Inu ja nai desu.",en:"Není to pes."},
         {num:"2",jp:"すき じゃない です。",ro:"Suki ja nai desu.",en:"Nemám to rád."},
       ]},
      {title:"'One' pronoun — no po adjektivu",
       body:"No za přídavným jménem nebo barvou vytváří zájmeno 'ten ___ kus'.",
       examples:[
         {num:"1",jp:"あか の が すき です。",ro:"Aka no ga suki desu.",en:"Mám rád ten červený."},
         {num:"2",jp:"おいしい の が すき です。",ro:"",en:"Mám rád ten chutný."},
       ]},
      {title:"Ja a (じゃあ) — well then",
       body:"Ja a se říká na začátku věty jako přechod nebo závěr.",
       examples:[
         {num:"1",jp:"じゃあ、いぬ が すき ですか。",ro:"Ja a, inu ga suki desu ka.",en:"No tak, máš rád psy?"},
       ]},
    ]},
    {type:"tip", text:"Kirai (嫌い) zní v japonštině poměrně tvrdě. V běžné konverzaci je zdvořilejší 'suki ja nai desu' (nemám to rád) než 'kirai desu'.", warn:true},
    {type:"kana", rows:[...H_NA]},
    {type:"qa", title:"Q&A cvičení", titleJp:"Q&A", pairs:[
      {en:"Do you like it?",jp:"すき ですか。"},
      {en:"Yes, I like it.",jp:"はい、すき です。"},
      {en:"No, I don't like it.",jp:"いいえ、すき じゃない です。"},
      {en:"What do you like?",jp:"なに が すき ですか。"},
      {en:"I like shopping.",jp:"かいもの が すき です。"},
    ]},
    {type:"sentence", jp:"なに が すき ですか。どっち が すき ですか。", en:"Co máš rád? Který preferuješ?"},
    {type:"vocab", groupTitle:"Ovoce (果物)", items:[
      {jp:"りんご",kana:"りんご",romaji:"ringo",en:"jablko"},
      {jp:"バナナ",kana:"バナナ",romaji:"banana",en:"banán"},
      {jp:"いちご",kana:"いちご",romaji:"ichigo",en:"jahoda"},
      {jp:"すいか",kana:"すいか",romaji:"suika",en:"meloun"},
      {jp:"もも",kana:"もも",romaji:"momo",en:"broskev"},
      {jp:"みかん",kana:"みかん",romaji:"mikan",en:"mandarinka"},
    ]},
  ],
  flashcardGroups:[
    {name:"Hiragana なにぬねの", cards: kanaCards(H_NA)},
    {name:"Suki / Kirai výrazy", cards:[
      {front:"すき",frontKana:"",frontRo:"suki",back:"mít rád"},
      {front:"きらい",frontKana:"",frontRo:"kirai",back:"nemít rád"},
      {front:"だいすき",frontKana:"",frontRo:"daisuki",back:"zbožňovat"},
      {front:"だいきらい",frontKana:"",frontRo:"daikirai",back:"nesnášet"},
      {front:"おいしい",frontKana:"",frontRo:"oishii",back:"chutný"},
      {front:"すき じゃない",frontKana:"すきじゃない",frontRo:"suki ja nai",back:"nemám to rád (zdvořilý zápor)"},
    ]},
  ],
  quiz:[
    {q:"Jak řekneš 'Mám rád kočky'?",
     options:["ねこ は すき です","わたし は ねこ を すき です","わたし は ねこ が すき です","ねこ が わたし すき です"], correct:2},
    {q:"Jak zdvořile řekneš 'Nemám to rád'?",
     options:["きらい です","すき じゃない です","だいきらい です","きらい じゃない です"], correct:1},
    {q:"Co znamená 'aka no ga suki desu'?",
     options:["Mám rád červenou obecně","Mám rád ten červený kus","Červená je moje oblíbená","Nemám rád červenou"], correct:1},
  ]
},

/* ═══════════════════════ LESSON 6 ═══════════════════════ */
{
  id:"l6", eyebrow:"Lekce 6",
  title:"Wanting and Not Wanting",
  subtitle:"Chtít a nechtít · Hiragana はひふへほ",
  about:{
    before:["I-adjektiva a negace -kunai","Suki/kirai + が"],
    goals:["Hoshii (ほしい) — chtít věc","Negace I-adj. s -kunai","Čísla a peníze","Směrová částice へ"],
    teachers:["Hoshii je I-adjektivum — negace hoshikunai","Nezaměňuj ja nai (podst.jm.) a -kunai (I-adj.)"]
  },
  blocks:[
    {type:"words", headers:["Progressive","Kana","Kanji","Česky"], rows:[
      ["hoshii","ほしい","欲しい","chtít (věc)"],
      ["atarashii","あたらしい","新しい","nový"],
      ["furui","ふるい","古い","starý"],
      ["atsui","あつい","暑い・熱い","horký"],
      ["samui","さむい","寒い","studený (vzduch)"],
      ["tsumetai","つめたい","冷たい","studený (na dotek)"],
      ["nurui","ぬるい","温い","vlažný"],
      ["okane","おかね","お金","peníze"],
      ["en","えん","円","yen"],
      ["doru","ドル","ドル","dolar"],
      ["mizu","みず","水","voda"],
      ["koora","コーラ","コーラ","cola"],
      ["kekkoudesu","けっこうです","結構です","Ne, děkuji."],
      ["mochiron","もちろん","もちろん","samozřejmě"],
    ]},
    {type:"phrases", items:[
      {num:"1",en:"No, thank you. / I'm fine.",jp:"けっこう です。",ro:"Kekkoudesu."},
    ]},
    {type:"culture", title:"Kun (くん) a Chan (ちゃん)",
      text:"Kun (くん) = pro mladší muže v práci/škole. Chan (ちゃん) = pro děti, blízké přátele, dívky. NIKDY pro nadřízené nebo cizí lidi. Chyba s oslovením může být velmi neuctivá!"},
    {type:"grammar", points:[
      {title:"Negace I-adjektiv: -i → -kunai",
       body:"Všechna I-adjektiva neguj odtržením -i a přidáním -kunai. VÝJIMKA: ii (よい) → yokunai, NE ikunai!",
       formula:"[adj] minus i + kunai",
       examples:[
         {num:"1",jp:"あたらしい → あたらしくない",ro:"",en:"nový → není nový"},
         {num:"2",jp:"おいしい → おいしくない",ro:"",en:"chutný → nechutný"},
         {num:"3",jp:"いい → よくない ❗",ro:"ii → yokunai",en:"dobrý → není dobrý (VÝJIMKA!)"},
       ]},
      {title:"Hoshii (欲しい) — chtít věc",
       body:"Hoshii je I-adjektivum. Věc, kterou chceš, dostává が. Negace: hoshikunai.",
       formula:"[věc] ga hoshii desu",
       examples:[
         {num:"1",jp:"あたらしい テレビ が ほしい です。",ro:"",en:"Chci novou televizi."},
         {num:"2",jp:"ふるい くるま が ほしくない です。",ro:"",en:"Nechci staré auto."},
         {num:"3",jp:"なに が ほしい ですか。",ro:"Nani ga hoshii desu ka.",en:"Co chceš?"},
       ]},
      {title:"Směrová částice へ (e)",
       body:"He (へ) jako směrová částice se čte 'e' — označuje směr pohybu, cíl.",
       examples:[
         {num:"1",jp:"にほん へ いきます。",ro:"Nihon e ikimasu.",en:"Jedu do Japonska."},
         {num:"2",jp:"がっこう へ いきます。",ro:"",en:"Jdu do školy."},
       ]},
    ]},
    {type:"kana", rows:[...H_HA]},
    {type:"tip", text:"ふ (fu) — výjimka v HA-řadě. Vyslovuje se 'fu' (mezi f a h), ne 'hu'. Jemně fouknout vzduch přes spodní ret — bez plného kontaktu zubů."},
    {type:"qa", title:"Q&A cvičení J→E", titleJp:"Q&A J→E", pairs:[
      {jp:"なに が ほしい ですか。",en:"Co chceš?"},
      {jp:"あたらしい くるま が ほしい です。",en:"Chci nové auto."},
      {jp:"あなた の くるま は あたらしい ですか。",en:"Je tvoje auto nové?"},
      {jp:"いいえ、ふるい です。",en:"Ne, je staré."},
      {jp:"コーラ が ほしい ですか。",en:"Chceš colu?"},
      {jp:"いいえ、ほしくない です。",en:"Ne, nechci."},
    ]},
    {type:"sentence", jp:"どっち が ほしい ですか。", en:"Který chceš?"},
    {type:"vocab", groupTitle:"Doprava (交通 koutsuu)", items:[
      {jp:"でんしゃ",kana:"でんしゃ",romaji:"densha",en:"vlak"},
      {jp:"バス",kana:"バス",romaji:"basu",en:"autobus"},
      {jp:"タクシー",kana:"タクシー",romaji:"takushii",en:"taxi"},
      {jp:"じてんしゃ",kana:"じてんしゃ",romaji:"jitensha",en:"kolo"},
      {jp:"ひこうき",kana:"ひこうき",romaji:"hikouki",en:"letadlo"},
      {jp:"ふね",kana:"ふね",romaji:"fune",en:"loď"},
    ]},
  ],
  flashcardGroups:[
    {name:"Hiragana はひふへほ", cards: kanaCards(H_HA)},
    {name:"I-adjektiva — negace", cards:[
      {front:"あたらしい",frontKana:"",frontRo:"atarashii",back:"nový → atarashikunai"},
      {front:"ふるい",frontKana:"",frontRo:"furui",back:"starý → furukunai"},
      {front:"あつい",frontKana:"",frontRo:"atsui",back:"horký → atsukunai"},
      {front:"さむい",frontKana:"",frontRo:"samui",back:"studený → samukunai"},
      {front:"つめたい",frontKana:"",frontRo:"tsumetai",back:"studený na dotek → tsumetakunai"},
      {front:"おいしい",frontKana:"",frontRo:"oishii",back:"chutný → oishikunai"},
      {front:"いい",frontKana:"",frontRo:"ii",back:"dobrý → YOKUNAI (výjimka!)"},
    ]},
    {name:"Hoshii — přání", cards:[
      {front:"ほしい",frontKana:"",frontRo:"hoshii",back:"chci (věc)"},
      {front:"ほしくない",frontKana:"",frontRo:"hoshikunai",back:"nechci"},
      {front:"もちろん",frontKana:"",frontRo:"mochiron",back:"samozřejmě"},
    ]},
  ],
  quiz:[
    {q:"Jak negujeme I-adjektivum 'atarashii' (nový)?",
     options:["atarashii ja nai","atarashikunai","atarashii nai","atarashide wa nai"], correct:1},
    {q:"Jak řekneš 'Chci nové auto'?",
     options:["あたらしい くるま は ほしい です","あたらしい くるま が ほしい です","あたらしい くるま を ほしい です","くるま は あたらしい ほしい"], correct:1},
    {q:"Jaký je negativní tvar 'ii' (dobrý)?",
     options:["ikunai","iinai","yokunai","ii ja nai"], correct:2,
     explain:"Ii → yokunai. Výjimka! NE ikunai."},
  ]
},

/* ═══════════════════════ LESSON 7 ═══════════════════════ */
{
  id:"l7", eyebrow:"Lekce 7",
  title:"Locations",
  subtitle:"Místa · Hiragana まみむめも",
  about:{
    before:["I-adjektiva a negace","No pro přivlastnění"],
    goals:["Kde se věci nacházejí","Pravidla は vs. が","Použití demo (ale)","Yokunai vs. ikunai"],
    teachers:["Ko-so-a-do má i formy pro místa: koko/soko/asoko/doko","Pravidla は vs. が se naučíš praxí — nezahlcuj se teorií najednou"]
  },
  blocks:[
    {type:"words", headers:["Progressive","Kana","Kanji","Česky"], rows:[
      ["doko","どこ","どこ","kde?"],
      ["koko","ここ","ここ","tady"],
      ["soko","そこ","そこ","tam (u posluchače)"],
      ["asoko","あそこ","あそこ","tamhle (daleko)"],
      ["soto","そと","外","venku"],
      ["naka","なか","中","uvnitř"],
      ["resutoran","レストラン","レストラン","restaurace"],
      ["nihon","にほん","日本","Japonsko"],
      ["demo","でも","でも","ale, však"],
      ["ii / yoi","いい・よい","良い","dobrý, hezký"],
      ["ookii","おおきい","大きい","velký"],
      ["chiisai","ちいさい","小さい","malý"],
    ]},
    {type:"phrases", items:[
      {num:"1",en:"I'm hungry.",jp:"おなか が すいて います。",ro:"Onaka ga suite imasu."},
      {num:"2",en:"I'm full.",jp:"おなか が いっぱい です。",ro:"Onaka ga ippai desu."},
      {num:"3",en:"I'm thirsty.",jp:"のど が かわいて います。",ro:"Nodo ga kawaite imasu."},
    ]},
    {type:"grammar", points:[
      {title:"Demo (でも) — ale",
       body:"Demo se dává na ZAČÁTEK druhé věty. Nespojuje věty uprostřed.",
       formula:"(Věta 1). Demo, (Věta 2).",
       examples:[
         {num:"1",jp:"フルーツ は おいしい です。でも、おなか が いっぱい です。",ro:"",en:"Ovoce je chutné. Ale jsem sytý."},
         {num:"2",jp:"コーラ は つめたくない です。でも、ほしい です。",ro:"",en:"Cola není studená. Ale chci ji."},
       ]},
      {title:"5 pravidel は vs. が",
       body:"Nejčastější otázka začátečníků — přehled klíčových pravidel:",
       examples:[
         {num:"#1",jp:"NIKDY は přímo za tázacím slovem.",ro:"",en:"Nani GA suki desu ka ✓ / Nani WA suki desu ka ✗"},
         {num:"#2",jp:"は pro srovnání a zdůraznění.",ro:"",en:"Suika WA oishii desu. (Meloun je fakt dobrý — důraz)"},
         {num:"#3",jp:"は a が mohou být ve stejné větě.",ro:"",en:"Watashi WA neko GA suki desu."},
         {num:"#4",jp:"は pro nová témata konverzace.",ro:"",en:"Nové téma → は. Pokračování → が nebo vynechání."},
         {num:"#5",jp:"V neformálním hovoru se obě běžně vynechávají.",ro:"",en:"Neko suki? (chápe se z kontextu)"},
       ]},
      {title:"Yokunai vs. ikunai",
       body:"Ii (いい) má negativum vždy yokunai — NIKDY ikunai.",
       examples:[
         {num:"1",jp:"この レストラン は よくない です。",ro:"",en:"Tato restaurace není dobrá."},
       ]},
    ]},
    {type:"kana", rows:[...H_MA]},
    {type:"dialogue", title:"Mini rozhovor J→E", lines:[
      {speaker:"A:", jp:"たなか さん の うち は あそこ ですか。", en:"Je Tanakův dům tamhle?"},
      {speaker:"B:", jp:"いいえ、ちがいます。そこ です。", en:"Ne. Je tam."},
      {speaker:"A:", jp:"えっ、どこ ですか。", en:"Hmm, kde to je?"},
      {speaker:"B:", jp:"きいろい うち が わたし の です。", en:"Žlutý dům je můj."},
    ]},
    {type:"sentence", jp:"レストラン は どこ ですか。", en:"Kde je restaurace?"},
    {type:"vocab", groupTitle:"Místa (場所 basho)", items:[
      {jp:"がっこう",kana:"がっこう",romaji:"gakkou",en:"škola"},
      {jp:"びょういん",kana:"びょういん",romaji:"byouin",en:"nemocnice"},
      {jp:"ぎんこう",kana:"ぎんこう",romaji:"ginkou",en:"banka"},
      {jp:"としょかん",kana:"としょかん",romaji:"toshokan",en:"knihovna"},
      {jp:"えき",kana:"えき",romaji:"eki",en:"nádraží"},
      {jp:"くうこう",kana:"くうこう",romaji:"kuukou",en:"letiště"},
      {jp:"こうえん",kana:"こうえん",romaji:"kouen",en:"park"},
    ]},
  ],
  flashcardGroups:[
    {name:"Hiragana まみむめも", cards: kanaCards(H_MA)},
    {name:"Místa — ko-so-a-do", cards:[
      {front:"ここ",frontKana:"",frontRo:"koko",back:"tady (u mluvčího)"},
      {front:"そこ",frontKana:"",frontRo:"soko",back:"tam (u posluchače)"},
      {front:"あそこ",frontKana:"",frontRo:"asoko",back:"tamhle (daleko)"},
      {front:"どこ",frontKana:"",frontRo:"doko",back:"kde?"},
      {front:"そと",frontKana:"",frontRo:"soto",back:"venku"},
      {front:"なか",frontKana:"",frontRo:"naka",back:"uvnitř"},
    ]},
  ],
  quiz:[
    {q:"Jak japonsky řekneš 'Kde je to?'",
     options:["なに ですか","どれ ですか","どこ ですか","だれ ですか"], correct:2},
    {q:"Co znamená あそこ (asoko)?",
     options:["tady u mluvčího","tam u posluchače","tamhle daleko od obou","kde?"], correct:2},
    {q:"Jak správně řekneš 'tamhle je restaurace'?",
     options:["あそこ が レストラン は です","レストラン は あそこ です","あそこ の レストラン は です","レストランどこ"], correct:1},
    {q:"Kdy NELZE použít は za tázacím slovem?",
     options:["V negativních větách","VŽDY — tázací slovo + が, ne は","Jen v přítomném čase","Nikdy — vždy jde は"], correct:1},
  ]
},

/* ═══════════════════════ LESSON 8 ═══════════════════════ */
{
  id:"l8", eyebrow:"Lekce 8",
  title:"Verbs and Going Places",
  subtitle:"Slovesa a pohyb · Hiragana やゆよ",
  about:{
    before:["Hiragana MA-řada","Základy は vs. が"],
    goals:["Základní japonská slovesa","Přítomný/budoucí čas -masu","Minulý čas -mashita","Záporné tvary","Cíl pohybu s に"],
    teachers:["Jedno sloveso platí pro všechny osoby — žádná shoda","Rozlišuj ikimasu (jdu) vs. kimasu (přijdu)"]
  },
  blocks:[
    {type:"words", headers:["Progressive","Kana","Kanji","Česky"], rows:[
      ["ikimasu","いきます","行きます","jít, jet"],
      ["kimasu","きます","来ます","přijít"],
      ["kaerimasu","かえります","帰ります","vrátit se domů"],
      ["tabemasu","たべます","食べます","jíst"],
      ["nomimasu","のみます","飲みます","pít"],
      ["mimasu","みます","見ます","dívat se"],
      ["kikimasu","ききます","聞きます","poslouchat"],
      ["yomimasu","よみます","読みます","číst"],
      ["kakimasu","かきます","書きます","psát"],
      ["shimasu","します","します","dělat"],
      ["wakarimasu","わかります","分かります","rozumět"],
      ["gakkou","がっこう","学校","škola"],
      ["ie","いえ","家","dům, domov"],
    ]},
    {type:"phrases", items:[
      {num:"1",en:"Please give me ___.",jp:"___ を ください。",ro:"___ o kudasai."},
      {num:"2",en:"I'd like ___, please. (zdvořilejší)",jp:"___ を おねがいします。",ro:"___ o onegaishimasu."},
    ]},
    {type:"grammar", points:[
      {title:"Slovesa — tvar -masu",
       body:"Zdvořilá přítomná/budoucí forma vždy končí na -masu. Jedno sloveso pro všechny osoby!",
       formula:"[místo] ni/e + [sloveso]-masu",
       examples:[
         {num:"1",jp:"がっこう に いきます。",ro:"Gakkou ni ikimasu.",en:"Jdu do školy."},
         {num:"2",jp:"にほん へ いきます。",ro:"Nihon e ikimasu.",en:"Jedu do Japonska."},
         {num:"3",jp:"ともだち が きます。",ro:"Tomodachi ga kimasu.",en:"Přítel přijde."},
       ]},
      {title:"Minulý čas: -masu → -mashita",
       body:"Prostě vyměníš -masu za -mashita.",
       examples:[
         {num:"1",jp:"がっこう に いきました。",ro:"",en:"Šel jsem do školy."},
         {num:"2",jp:"ラーメン を たべました。",ro:"",en:"Snědl jsem ramen."},
       ]},
      {title:"Záporný přítomný: -masu → -masen",
       body:"Pro záporný přítomný/budoucí čas.",
       examples:[
         {num:"1",jp:"がっこう に いきません。",ro:"",en:"Nejdu do školy."},
         {num:"2",jp:"にほんご が わかりません。",ro:"",en:"Nerozumím japonsky."},
       ]},
      {title:"Záporný minulý: -masendeshita",
       body:"Kombinace masen + deshita.",
       examples:[
         {num:"1",jp:"がっこう に いきませんでした。",ro:"",en:"Nešel jsem do školy."},
       ]},
    ]},
    {type:"kana", rows:[...H_YA]},
    {type:"tip", text:"YA-řada je neúplná: や、ゆ、よ — chybí yi a ye (ty zvuky v japonštině neexistují). Jsou jen tři znaky."},
    {type:"qa", title:"Q&A cvičení E→J", titleJp:"Q&A E→J", pairs:[
      {en:"Where are you going?",jp:"どこ に いきますか。"},
      {en:"I am going to Japan.",jp:"にほん に いきます。"},
      {en:"Did you return home?",jp:"いえ に かえりましたか。"},
      {en:"No, I went to a friend's house.",jp:"いいえ、ともだち の いえ に いきました。"},
      {en:"I will go in March.",jp:"さんがつ に いきます。"},
    ]},
    {type:"sentence", jp:"がっこう に いきます。", en:"Jdu do školy."},
    {type:"vocab", groupTitle:"Jídlo (食べ物 tabemono)", items:[
      {jp:"ラーメン",kana:"ラーメン",romaji:"raamen",en:"ramen"},
      {jp:"すし",kana:"すし",romaji:"sushi",en:"sushi"},
      {jp:"てんぷら",kana:"てんぷら",romaji:"tenpura",en:"tempura"},
      {jp:"みそしる",kana:"みそしる",romaji:"misoshiru",en:"miso polévka"},
      {jp:"おちゃ",kana:"おちゃ",romaji:"ocha",en:"zelený čaj"},
      {jp:"コーヒー",kana:"コーヒー",romaji:"koohii",en:"káva"},
    ]},
  ],
  flashcardGroups:[
    {name:"Hiragana やゆよ", cards: kanaCards(H_YA)},
    {name:"Slovesa (masu-tvar)", cards:[
      {front:"行きます",frontKana:"いきます",frontRo:"ikimasu",back:"jít / jet"},
      {front:"来ます",frontKana:"きます",frontRo:"kimasu",back:"přijít"},
      {front:"帰ります",frontKana:"かえります",frontRo:"kaerimasu",back:"vrátit se"},
      {front:"食べます",frontKana:"たべます",frontRo:"tabemasu",back:"jíst"},
      {front:"飲みます",frontKana:"のみます",frontRo:"nomimasu",back:"pít"},
      {front:"見ます",frontKana:"みます",frontRo:"mimasu",back:"dívat se"},
      {front:"聞きます",frontKana:"ききます",frontRo:"kikimasu",back:"poslouchat"},
      {front:"読みます",frontKana:"よみます",frontRo:"yomimasu",back:"číst"},
      {front:"書きます",frontKana:"かきます",frontRo:"kakimasu",back:"psát"},
      {front:"します",frontKana:"します",frontRo:"shimasu",back:"dělat"},
    ]},
    {name:"Časy sloves", cards:[
      {front:"ikimasu",frontKana:"いきます",frontRo:"",back:"Jdu (přítomný/budoucí)"},
      {front:"ikimashita",frontKana:"いきました",frontRo:"",back:"Šel jsem (minulý)"},
      {front:"ikimasen",frontKana:"いきません",frontRo:"",back:"Nejdu (záporný přítomný)"},
      {front:"ikimasendeshita",frontKana:"いきませんでした",frontRo:"",back:"Nešel jsem (záporný minulý)"},
    ]},
  ],
  quiz:[
    {q:"Jak se řekne 'Šel jsem do školy'?",
     options:["がっこう に いきます","がっこう に いきました","がっこう に いきません","がっこう に いきませんでした"], correct:1,
     explain:"-masu = přítomný/budoucí, -mashita = minulý."},
    {q:"Jak se řekne 'Nešel jsem'?",
     options:["いきません","いきました","いきませんでした","いきましたか"], correct:2},
    {q:"Co označuje に (ni) v kontextu pohybu?",
     options:["Odkud přicházím","Kam jdu — cíl pohybu","Kdy jdu","S kým jdu"], correct:1},
    {q:"Jak se japonsky řekne 'přijít'?",
     options:["ikimasu","kaerimasu","kimasu","shimasu"], correct:2},
  ]
},

/* ═══════════════════════ LESSON 9 ═══════════════════════ */
{
  id:"l9", eyebrow:"Lekce 9",
  title:"Days, Weeks, and Years",
  subtitle:"Dny, týdny, roky · Hiragana らりるれろ",
  about:{
    before:["Základní slovesa (-masu, -mashita)","Čísla a měsíce"],
    goals:["Dny v týdnu","Vyjádřit rok","Výrazy pro minulý/příští týden, rok…","Minulý čas deshita"],
    teachers:["Dny = logické: getsu=měsíc, ka=oheň, sui=voda, moku=dřevo, kin=zlato, do=půda, nichi=slunce","Pořadí data: ROK → MĚSÍC → DEN"]
  },
  blocks:[
    {type:"words", headers:["Progressive","Kana","Kanji","Česky"], rows:[
      ["nan youbi","なんようび","何曜日","který den?"],
      ["ima","いま","今","teď"],
      ["kinoo","きのう","昨日","včera"],
      ["kyoo","きょう","今日","dnes"],
      ["ashita","あした","明日","zítra"],
      ["asatte","あさって","明後日","pozítří"],
      ["senshu","せんしゅう","先週","minulý týden"],
      ["konshuu","こんしゅう","今週","tento týden"],
      ["raishuu","らいしゅう","来週","příští týden"],
      ["kyonen","きょねん","去年","minulý rok"],
      ["kotoshi","ことし","今年","letos"],
      ["rainen","らいねん","来年","příští rok"],
      ["tanjoubi","たんじょうび","誕生日","narozeniny"],
    ]},
    {type:"phrases", items:[
      {num:"1",en:"In what year were you born?",jp:"なんねん うまれ ですか。",ro:"Nan nen umare desu ka."},
      {num:"2",en:"I was born in ___.",jp:"___ ねん うまれ です。",ro:"___ nen umare desu."},
    ]},
    {type:"culture", title:"Japan's New Year (お正月 o-shōgatsu)",
      text:"Japonský Nový rok je nejdůležitějším svátkem — obchodní domy jsou zavřeny, rodiny se scházejí, navštěvují chrámy (hatsumoude) a jedí speciální jídla (osechi). Posílají si novoroční pohlednice (nengajou), které musí dorazit přesně 1. ledna."},
    {type:"words", headers:["Japonsky","Kana","Kanji","Česky"], rows:[
      ["getsuyoubi","げつようび","月曜日","pondělí (月=měsíc)"],
      ["kayoubi","かようび","火曜日","úterý (火=oheň)"],
      ["suiyoubi","すいようび","水曜日","středa (水=voda)"],
      ["mokuyoubi","もくようび","木曜日","čtvrtek (木=dřevo)"],
      ["kinyoubi","きんようび","金曜日","pátek (金=zlato)"],
      ["doyoubi","どようび","土曜日","sobota (土=půda)"],
      ["nichiyoubi","にちようび","日曜日","neděle (日=slunce)"],
    ]},
    {type:"tip", text:"Japonské dny jsou pojmenovány po 7 kosmických elementech — Slunce, Měsíc, Oheň, Voda, Dřevo, Kov, Půda. Stejný systém jako v čínštině a korejštině."},
    {type:"grammar", points:[
      {title:"Vyjadřování roku",
       body:"Rok = číslo + nen (年). Musíš říct CELÉ číslo — nikoliv po dvou číslicích jako v angličtině.",
       examples:[
         {num:"1",jp:"せんきゅうひゃくはちじゅうねん",ro:"sen kyuu hyaku hachi juu nen",en:"rok 1980"},
         {num:"2",jp:"にせんじゅうしちねん",ro:"nisen juu shichi nen",en:"rok 2017"},
       ]},
      {title:"Pořadí dat",
       body:"Vždy od největšího: ROK → MĚSÍC → DEN (opak anglického pořadí).",
       formula:"[rok] nen [měsíc] gatsu [den] nichi",
       examples:[
         {num:"1",jp:"にせんごねん ごがつ じゅういちにち",ro:"",en:"11. května 2005"},
       ]},
      {title:"Minulý čas desu → deshita",
       body:"Minulé 'bylo/byl/byla' = deshita (でした).",
       examples:[
         {num:"1",jp:"きのう は げつようび でした。",ro:"Kinoo wa getsuyoubi deshita.",en:"Včera bylo pondělí."},
       ]},
    ]},
    {type:"kana", rows:[...H_RA]},
    {type:"qa", title:"Q&A cvičení E→J", titleJp:"Q&A E→J", pairs:[
      {en:"What day is it?",jp:"なんようび ですか。"},
      {en:"Today is Saturday.",jp:"きょう は どようび です。"},
      {en:"When is the party?",jp:"パーティー は いつ ですか。"},
      {en:"It was Wednesday.",jp:"すいようび でした。"},
    ]},
    {type:"sentence", jp:"きょう は なんようび ですか。", en:"Jaký je dnes den?"},
    {type:"vocab", groupTitle:"Čas (時間 jikan)", items:[
      {jp:"いちじ",kana:"いちじ",romaji:"ichiji",en:"1 hodina"},
      {jp:"なんじ",kana:"なんじ",romaji:"nanji",en:"kolik hodin?"},
      {jp:"ごぜん",kana:"ごぜん",romaji:"gozen",en:"dopoledne (AM)"},
      {jp:"ごご",kana:"ごご",romaji:"gogo",en:"odpoledne (PM)"},
      {jp:"はん",kana:"はん",romaji:"han",en:"půl (12:30 = じゅうにじはん)"},
    ]},
  ],
  flashcardGroups:[
    {name:"Hiragana らりるれろ", cards: kanaCards(H_RA)},
    {name:"Dny v týdnu", cards:[
      {front:"月曜日",frontKana:"げつようび",frontRo:"getsuyoubi",back:"pondělí"},
      {front:"火曜日",frontKana:"かようび",frontRo:"kayoubi",back:"úterý"},
      {front:"水曜日",frontKana:"すいようび",frontRo:"suiyoubi",back:"středa"},
      {front:"木曜日",frontKana:"もくようび",frontRo:"mokuyoubi",back:"čtvrtek"},
      {front:"金曜日",frontKana:"きんようび",frontRo:"kinyoubi",back:"pátek"},
      {front:"土曜日",frontKana:"どようび",frontRo:"doyoubi",back:"sobota"},
      {front:"日曜日",frontKana:"にちようび",frontRo:"nichiyoubi",back:"neděle"},
    ]},
    {name:"Časové výrazy", cards:[
      {front:"きのう",frontKana:"",frontRo:"kinoo",back:"včera"},
      {front:"きょう",frontKana:"",frontRo:"kyoo",back:"dnes"},
      {front:"あした",frontKana:"",frontRo:"ashita",back:"zítra"},
      {front:"せんしゅう",frontKana:"",frontRo:"senshu",back:"minulý týden"},
      {front:"らいしゅう",frontKana:"",frontRo:"raishuu",back:"příští týden"},
      {front:"きょねん",frontKana:"",frontRo:"kyonen",back:"minulý rok"},
      {front:"ことし",frontKana:"",frontRo:"kotoshi",back:"letos"},
      {front:"らいねん",frontKana:"",frontRo:"rainen",back:"příští rok"},
    ]},
  ],
  quiz:[
    {q:"Jak se řekne 'pondělí'?",
     options:["かようび","げつようび","きんようび","にちようび"], correct:1},
    {q:"V jakém pořadí se v japonštině uvádí datum?",
     options:["Den → Měsíc → Rok","Měsíc → Den → Rok","Rok → Měsíc → Den","Rok → Den → Měsíc"], correct:2},
    {q:"Co znamená でした (deshita)?",
     options:["Je to","Bylo to / Byl/a jsem","Není to","Bude to"], correct:1},
    {q:"Jak se řekne 'příští rok'?",
     options:["きょねん","ことし","らいねん","せんねん"], correct:2},
  ]
},

/* ═══════════════════════ LESSON 10 ═══════════════════════ */
{
  id:"l10", eyebrow:"Lekce 10",
  title:"Counters",
  subtitle:"Čítací přípony · Hiragana わをん + složené kany",
  about:{
    before:["Celá hiragana (řady A–RA)","Čísla 1–1000"],
    goals:["Základní čítací přípony","Hitotsu…too (obecné počítání)","Čítač mai, hon, ko, satsu","Složené kany (youon)"],
    teachers:["Čítací přípony jsou charakteristická vlastnost japonštiny","Hitotsu série (do 10) funguje univerzálně"]
  },
  blocks:[
    {type:"phrases", items:[
      {num:"1",en:"Please give me ___.",jp:"___ を ください。",ro:"___ o kudasai."},
      {num:"2",en:"I'd like ___. (zdvořilejší)",jp:"___ を おねがいします。",ro:"___ o onegaishimasu."},
    ]},
    {type:"grammar", points:[
      {title:"Japonské čítací přípony",
       body:"Různé kategorie věcí mají různé čítače. Nejdůležitější:",
       examples:[
         {num:"ひとつ〜とお",jp:"ひとつ / ふたつ / みっつ / よっつ / いつつ…",ro:"hitotsu/futatsu/mittsu/yottsu/itsutsu",en:"Obecné věci (1–10) — nejflexibilnější"},
         {num:"まい",jp:"いちまい / にまい / さんまい",ro:"ichimai / nimai / sanmai",en:"Ploché věci: papíry, lístky, talíře"},
         {num:"ほん",jp:"いっぽん / にほん / さんぼん",ro:"ippon / nihon / sanbon",en:"Tyčovité věci: tužky, lahve"},
         {num:"こ",jp:"いっこ / にこ / さんこ",ro:"ikko / niko / sanko",en:"Malé kulaté věci: jablka, vajíčka"},
         {num:"さつ",jp:"いっさつ / にさつ / さんさつ",ro:"issatsu / nisatsu / sansatsu",en:"Svázané věci: knihy, sešity"},
       ]},
    ]},
    {type:"kana", rows:[...H_WA, ...H_N]},
    {type:"tip", text:"を (o) jako částice přímého předmětu, ん (n) jako samostatná souhláska — tyto dvě kany uzavírají základní hiraganu!"},
    {type:"h3", text:"Složené kany (拗音 youon)"},
    {type:"p", text:"Složené kany vznikají z consonantní kany + malé や、ゆ nebo よ. Malé ya/yu/yo musí být VIDITELNĚ menší. Jsou to jednoslabičné zvuky, ne dvouslabičné."},
    {type:"kana", rows:[...H_YOUON]},
    {type:"dialogue", title:"Krátký rozhovor — u sushi baru", lines:[
      {speaker:"Chef:", jp:"いらっしゃい。", en:"Vítejte!"},
      {speaker:"Jon:", jp:"すみません、いくら と はまち を ください。", en:"Promiňte, dám si lososí jikra a huňáče."},
      {speaker:"まさみ:", jp:"わたし は おみそしる を ひとつ と おちゃ を おねがいします。", en:"Pro mě miso polévku a čaj prosím."},
      {speaker:"Chef:", jp:"きょう は あまえび が おいしい です。", en:"Dnes jsou výborné sladké krevety."},
      {speaker:"まさみ:", jp:"じゃあ、それ を ひとつ、ください。", en:"Tak tu dám."},
    ]},
    {type:"sentence", jp:"ケーキ を みっつ ください。チケット を にまい おねがいします。", en:"Prosím tři dorty. Prosím dva lístky."},
    {type:"vocab", groupTitle:"Jídlo a pití", items:[
      {jp:"ラーメン",kana:"ラーメン",romaji:"raamen",en:"ramen"},
      {jp:"てんぷら",kana:"てんぷら",romaji:"tenpura",en:"tempura"},
      {jp:"みそしる",kana:"みそしる",romaji:"misoshiru",en:"miso polévka"},
      {jp:"おちゃ",kana:"おちゃ",romaji:"ocha",en:"zelený čaj"},
      {jp:"コーヒー",kana:"コーヒー",romaji:"koohii",en:"káva"},
      {jp:"ビール",kana:"ビール",romaji:"biiru",en:"pivo"},
    ]},
  ],
  flashcardGroups:[
    {name:"Hiragana わをん", cards: kanaCards([...H_WA, ...H_N])},
    {name:"Složené kany — youon", cards: kanaCards(H_YOUON)},
    {name:"Čítací přípony", cards:[
      {front:"ひとつ",frontKana:"",frontRo:"hitotsu",back:"jedno (obecný)"},
      {front:"ふたつ",frontKana:"",frontRo:"futatsu",back:"dvě"},
      {front:"みっつ",frontKana:"",frontRo:"mittsu",back:"tři"},
      {front:"よっつ",frontKana:"",frontRo:"yottsu",back:"čtyři"},
      {front:"いつつ",frontKana:"",frontRo:"itsutsu",back:"pět"},
      {front:"いちまい",frontKana:"",frontRo:"ichimai",back:"jeden plochý (papír, lístek)"},
      {front:"いっぽん",frontKana:"",frontRo:"ippon",back:"jedna tyčovitá (tužka, láhev)"},
      {front:"いっさつ",frontKana:"",frontRo:"issatsu",back:"jedna svázaná (kniha)"},
    ]},
  ],
  quiz:[
    {q:"Jak řekneš 'tři' při obecném počítání?",
     options:["さん","みっつ","さんこ","さんまい"], correct:1,
     explain:"Hitotsu/futatsu/mittsu… jsou obecné japonské čítače pro věci bez spec. kategorie."},
    {q:"Jaký čítač použiješ pro papíry a lístky?",
     options:["hon (ほん)","ko (こ)","mai (まい)","satsu (さつ)"], correct:2},
    {q:"Co jsou složené kany (youon)?",
     options:["Znaky pro cizí slova","Kombinace základní kany a malého ya/yu/yo","Zdvojené samohlásky","Dakuten verze"], correct:1},
    {q:"Jak japonsky řekneš 'Prosím dva lístky'?",
     options:["チケット を ふたつ ください","チケット を にまい ください","チケット を にこ ください","チケット を にほん ください"], correct:1},
  ]
},

]; // END BOOK1_PAGES
